baseurl = "/"
languageCode = "en-us"
title = "Stefan Eng's blog"
theme = "hugo-lithium"
googleAnalytics = "UA-45937616-1"
disqusShortname = "stefaneng"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/stefaneng"
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/stefaneng13"

[params]
    description = "Stefan Eng's blog on statistics."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

