---
title: Causal Inference Notes
draft: true
author: Stefan Eng
date: '2019-08-24'
slug: causal-inference-notes
categories:
  - statistics
tags:
  - causal-inference
output:
  blogdown::html_page:
    toc: no
    fig_width: 5
    fig_height: 5
csl: ../../static/bibtex/acm-sig-proceedings.csl
---


```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
## Load frequently used packages for blog posts
library(sessioninfo) # for session_info()
library(ggplot2)
library(here)

## For R images to display well in the RSS feed (disable for local preview)
# knitr::opts_knit$set(base.url = 'stefanengineering.com/post/')

# Don't show code by default
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, comment = NA, message = FALSE)
knitr::opts_knit$set(global.par = TRUE)

# CB Palette like ESL
cbPalette <- c(
  "#999999", "#E69F00", "#56B4E9", "#009E73",
  "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# My favorite theme
theme_set(ggplot2::theme_minimal(base_size = 15, base_family = "Arial"))
```

## Introduction
These are my notes from [Miguel Hernán's book on Causal Inference](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/)

### Sources of Random Variability
  1. Sampling Variability - sample value not equal to the population value we are trying to estimate.
  2. Nondeterministic counterfactuals - an individual's counterfactual outcomes might not be fixed in advance.

## Definitions
  - $Y^{a = 1}, Y^{a = 0}$ Potential outcomes, counterfactual outcomes. What would have occured, had the individual been treated with $A$ and also if not treated. May not actually occur.
    - If an individual, i, is treated, then $A = 1$ and $Y_i^{a = 1} = 1 = Y_i$
  - Causal effect for an individual: the treatment has a causal effect on the ind outcome Y if $ \not = Y^{a = 0}$
  - Consistency - An individual with observed outcome A equal to $a$ has observed outcome Y equal to his counterfactual outcome $Y^a$.
