---
title: Regression Modeling Strategries Notes
draft: true
author: Stefan Eng
date: '2019-07-28'
slug: regression-modeling-strategries-notes
categories:
  - R
tags: []
output:
  blogdown::html_page:
    toc: no
    fig_width: 5
    fig_height: 5
csl: ../../static/bibtex/acm-sig-proceedings.csl
---


```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
## Load frequently used packages for blog posts
library(sessioninfo) # for session_info()
library(ggplot2)

## For R images to display well in the RSS feed (disable for local preview)
# knitr::opts_knit$set(base.url = 'stefanengineering.com/post/')

# Don't show code by default
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, comment = NA, message = FALSE)
knitr::opts_knit$set(global.par = TRUE)

# CB Palette like ESL
cbPalette <- c(
  "#999999", "#E69F00", "#56B4E9", "#009E73",
  "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# My favorite theme
theme_set(ggplot2::theme_minimal(base_size = 15, base_family = "Arial"))
```

### Terms
  - **Calibration** (or **reliability**) - the ability of the model to predict future observations as well as the observations at hand.
    - **Calibration plot** - The plot of the observed responses against the predicted responses
  - **Shrinkage**
    1. (Related to the calibration plot) On the training data, the estimation process forces the slope to be one. When we use to model to predict new observations, overfitting will cause the slope of the calibration plot (i.e., the *shrinkage factor*) to be less than one. Generally low predictions will be too low and high predictions will be too high.
    2. Also used to describe method of preshrinking regression coefficients towards zero so that the calibration plot for new data will not need shrinkage as the calibration will be one.
