---
draft: true
title: Effect sizes and confidence intervals
author: Stefan Eng
date: '2020-06-17'
slug: effect-sizes-and-confidence-intervals
categories:
  - statistics
tags:
  - R
output:
  blogdown::html_page:
    toc: no
    fig_width: 5
    fig_height: 5
link-citations: yes
csl: ../../static/bibtex/acm-sig-proceedings.csl
bibliography: ../../static/bibtex/probability.bib
---


```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
## Load frequently used packages for blog posts
library(sessioninfo) # for session_info()
library(ggplot2)
library(here)

## For R images to display well in the RSS feed (disable for local preview)
# knitr::opts_knit$set(base.url = 'stefanengineering.com/post/')

# Don't show code by default
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, comment = NA, message = FALSE)
knitr::opts_knit$set(global.par = TRUE)

# CB Palette like ESL
cbPalette <- c(
  "#999999", "#E69F00", "#56B4E9", "#009E73",
  "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# My favorite theme
theme_set(ggplot2::theme_minimal(base_size = 15, base_family = "Arial"))
```

## Outline
Got the idea from the Laplace's demon bayesian seminar.
Paper: https://mucollective.northwestern.edu/files/2020-Visualizing-Inferential-Uncertainty.pdf
  - Standard deviations emphasize effect size
  - Standard error emphasize inference of parameter
  
  
```{r}
library(dplyr)
library(ggplot2)

n <- 100
x1 <- rnorm(n, mean = 10)
x2 <- rnorm(n, mean = 10.5)

d <- rbind(
  data.frame(x = x1, model = "10"),
  data.frame(x = x2, model = "10.5")
)

xr <- seq(7, 13, length.out = 1000)
yr1 <- dnorm(xr, mean = 10)
yr2 <- dnorm(xr + 0.5, mean = 10.5)
  
ggplot() +
  # Sample from distribution 1
  geom_histogram(data = data.frame(x = x1), 
                 aes(x = x, y=..density..), alpha = 0.5, fill = cbPalette[2]) +
  # Expected from distribution 1
  geom_line(data = data.frame(x = xr, y = yr1), color = cbPalette[2],
            aes(x = x, y = y))+
  # Sample from distribution 2
  geom_histogram(data = data.frame(x = x2), 
                 aes(x = x, y=..density..), alpha = 0.5, fill = cbPalette[3]) +
  # Expected from distribution 2
  geom_line(data = data.frame(x = xr + 0.5, y = yr2), color = cbPalette[3],
            aes(x = x, y = y))
```

```{r}
summary_d <- group_by(d, model) %>%
  summarize(mean = mean(x),
            sd = sd(x),
            sderr = sd(x) / sqrt(n()),
            low_ci = mean + sderr * qnorm(0.025),
            upper_ci = mean + sderr * qnorm(0.975))
summary_d
t.test(x1)$`conf.int`

ggplot(d, aes(x = model, y = x)) +
  geom_boxplot() +
  geom_jitter(width = 0.05, alpha = 0.25)
```

## Robustness

How robust is it to normality assumptions?
```{r}
boxplot(rt(1000, 100))
boxplot(rexp(100))
```

## References

## Reproducibility

```{r reproducibility, echo = FALSE}
## Reproducibility info
options(width = 120)
session_info()
```
